services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=n8n.srv954263.hstgr.cloud
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.srv954263.hstgr.cloud/
      - N8N_EDITOR_BASE_URL=https://n8n.srv954263.hstgr.cloud/

    volumes:
      - n8n_data:/home/node/.n8n

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data

  graphite:
    image: graphiteapp/graphite-statsd:latest
    restart: unless-stopped
    ports:
      - "8080:80"
      - "2003:2003/tcp"
      - "2004:2004/tcp"
      - "8125:8125/udp"
      - "8126:8126/tcp"
    volumes:
      - graphite_data:/var/lib/graphite
      - graphite_logs:/var/log/graphite
      - statsd_data:/opt/statsd

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  n8n_data:
  pgdata:
  neo4jdata:
  graphite_data:
  graphite_logs:
  statsd_data:
  pgadmin_data:
